- name: Install Python and producer script on producer node
  hosts: producers
  become: yes
  tasks:
    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install pulsar-client
      pip:
        name: pulsar-client==2.9.4
        executable: pip3

    # - name: Copy producer script
    #   copy:
    #     src: ../scripts/producer.py
    #     dest: /home/ubuntu/producer.py
    #     mode: '0755'
