- name: Prepare all hosts
  hosts: all
  become: yes
  tasks:
    - name: Update APT
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
